### ISSUE TITLE
No Party/guild Sounds...

### ISSUE THREAD

**Issue by ghost** [Xtortion/Tweaked-s1engine#1]
Well, It's pretty tweaked, Great job in that, Just 1 thing, There is no party sounds like party completion (im) or party making, along with party disband, Also guild sounds *join, or leave* are important, I mean When you're alt/tab and waiting for instance matching or battleground, you won't hear if it matched at all, and might get system kick *dropout*. :|
So if possible to let me know where to enable them, so I can edit them for myself only, Thanks in advance.

**Comment by Risenio** [comment]
Uhm, Totally nevermind! I just noticed that Max + Fixed sounds does actually have these inside of it, so I copied some out of there and pasted in pretty engine, and worked *gg...*, Thanks anyway.
